FROM debian:bookworm

RUN apt update && apt install -y php php-mysqli wget && rm -rf /var/lib/apt/lists/*
RUN mkdir -p /var/www/adminer \
 && wget -O /var/www/adminer/index.php https://www.adminer.org/latest.php

EXPOSE 8080
CMD ["php", "-S", "0.0.0.0:8080", "-t", "/var/www/adminer"]