FROM debian:bookworm

RUN apt update && apt install -y wget && rm -rf /var/lib/apt/lists/* \
    && wget -O /usr/local/bin/portainer https://github.com/portainer/portainer/releases/download/2.21.5/portainer-2.21.5-linux-amd64.tar.gz \
    && chmod +x /usr/local/bin/portainer

EXPOSE 9443
CMD ["portainer"]