FROM debian:bookworm

RUN apt update && apt install -y wget && rm -rf /var/lib/apt/lists/* \
 && wget -O /usr/local/bin/portainer https://github.com/portainer/portainer/releases/latest/download/portainer-linux-amd64 \
 && chmod +x /usr/local/bin/portainer

EXPOSE 9443
CMD ["portainer"]