FROM debian:bookworm

RUN apt update && apt install -y wget tar && rm -rf /var/lib/apt/lists/* \
    && wget https://github.com/portainer/portainer/releases/download/2.21.5/portainer-2.21.5-linux-amd64.tar.gz \
    && tar -xvf portainer-2.21.5-linux-amd64.tar.gz \
    && mv portainer/portainer /usr/local/bin/portainer \
    && rm -rf portainer-2.21.5-linux-amd64.tar.gz portainer

CMD ["/usr/local/bin/portainer"]