FROM debian:bookworm

RUN apt update && apt install -y redis-server && rm -rf /var/lib/apt/lists/*

RUN sed -i 's/bind 127.0.0.1/bind 0.0.0.0/' /etc/redis/redis.conf \
 && sed -i 's/# maxmemory <bytes>/maxmemory 256mb/' /etc/redis/redis.conf \
 && sed -i 's/# maxmemory-policy noeviction/maxmemory-policy allkeys-lru/' /etc/redis/redis.conf

CMD ["redis-server", "/etc/redis/redis.conf", "--protected-mode", "no"]